syntax on

set smarttab
set noerrorbells
set showmode
set number
set smartindent
set noswapfile
set tabstop=4
set shiftwidth=4
set softtabstop=4
set textwidth=79
set expandtab
set autoindent
set nobackup
set undodir=~/.vim/undodir
set undofile
set incsearch
set splitbelow